#!/bin/bash
OK=0
FAIL=0
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.fd8f27cc-ddc9-4298-beca-72db5dcd2852" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":480,"costo":378}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Keterolac 20 mg x 10 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.40921df4-9c4b-4311-b744-cdd4a6b01b50" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":2050,"costo":1642}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Ibuevanol rap accion x 10 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.24bb03eb-8562-4ced-ab23-cfdedfb581c7" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":1430,"costo":1139}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Bayaspirina C caliente -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.045bab4a-21df-42d6-9fb7-ad9536e228cf" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":2510,"costo":2041}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Tafirolito x 10 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.6d5d2dd4-8614-4800-a4d0-4fa233ea2699" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":1650,"costo":1289}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Tafirol 1G x 8 -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.15bd6310-7da9-4dac-af8e-56622a25572f" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":4650,"costo":3715}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Diclofenac B12 x 15 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.31d7b375-9344-431f-abef-dcca37e60dc9" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":2950,"costo":2358.72}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Tafirol Duo x10 -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.e2fc3797-3b7b-4e46-8c04-63828719fcbb" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":5900,"costo":4746}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Novalgina -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.45a70d4e-49a1-4021-8fd9-37e3ea499f55" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":3090,"costo":2462}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Actron 400 x10 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.c1bdd4f1-dd8c-41c6-83b6-70486b54fe7b" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":1890,"costo":1504}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Tafirol forte x tira -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.8851dee0-5d0d-42ae-bc83-1c60f03a023d" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":7200,"costo":5791}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Buscapina x10 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.1c8b3cbe-29cd-4e69-998e-0898c464c5df" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":2950,"costo":2336}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Next x10 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.536c8acd-17dd-4fe2-9c74-06fd1d684d0b" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":830,"costo":660}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Loratadina x10 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.795cc75b-c282-434e-b7bb-e81bfdf6d9be" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":710,"costo":570}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Solucion fisiologica 100ml -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.c70c17e9-ed5a-431d-80b3-79b633b3ca5e" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":550,"costo":435}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Diclofenac 75 x 15 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.d6457663-d8d0-4687-a279-f10d33aaa6b5" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":790,"costo":627}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Ibuprofeno 600 fabo x10 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.73569241-6039-4e0d-a204-fb9401cf1c83" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":3300,"costo":2628}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Actron Mujer x10 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.dfddc6d0-680d-4a8f-a739-a7647687e889" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":4200,"costo":3371}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Freen a mint chicle laxante -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.d2e41695-7c70-4526-8fc5-cb88b09952cc" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":3400,"costo":2734}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Actron plus x8 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.0f1ede24-8eaf-4ea3-86d2-056ea635b4ef" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":6900,"costo":5508}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Actron 600 x10 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.191445b6-8e3a-43af-931e-8c20d2acae09" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":400,"costo":320}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Bicarbonato de sodio -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.6edcbd7c-d0f0-4e98-9800-9fc7c205fb4a" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":2500,"costo":1987}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Dorixina x 10 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.2aec5241-92e5-4515-91c5-f9e9e1a517a1" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":2750,"costo":2189}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Ibuevanol FORTE x10 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.171dd858-ae88-4446-b4e8-771a8c447ba8" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":1150,"costo":932}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Test embarazo -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.5ea0c673-3408-46bf-9e4b-210f907b8690" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":450,"costo":363}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Agua oxigenada vol 10 -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.ef0dadb9-33c8-4646-8b5c-b4c9410d19a5" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":745,"costo":594}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Alikal x unidad -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.c1480fad-f328-4586-a0df-339a7e5b11e8" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":6750,"costo":5400}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Sertal x 10 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.03f58864-3e14-4fcc-aee5-8ad66ddc6dda" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":2700,"costo":2130}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Mejoral c/ paracetamol x 10 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.385afcfc-6558-4692-b006-778335f8b910" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":2450,"costo":1947}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Bayaspirina forte x10 -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.2eb7dc74-1d33-4a3f-8d66-69f6440868fa" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":500,"costo":399}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Keterolac 10 mg sublingual x10comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.98594b7b-143e-448d-89c6-b9c988cf794b" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":5000,"costo":3984}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Rennie x12 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.9c0856bb-5ae6-43c0-9fb9-6be5c1267d4d" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":2150,"costo":1730}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Cafiaspirina x10 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.9268ece5-f3aa-4807-96cb-a1ebafc422c1" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":1250,"costo":992}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Pastilla Carbon x10 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.95a8df50-0980-4ec5-8392-06f0dadf38ef" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":2000,"costo":1579}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Jarabe 4% -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.f130e639-3a9c-41c9-a621-2849140583bc" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":1870,"costo":1498}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Te Vick forte sobre -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.e119e004-aa95-4535-abfc-3b82d47c8c28" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":2020,"costo":1620}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Cefalexina 500 x8 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.cf46596d-0414-403d-858c-ac861fd3802f" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":4900,"costo":3910}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Sertal perlas x 10 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.bbb36247-79b5-4a19-bba7-025045a1e29f" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":760,"costo":605}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Diclofenac c/ pridinol x15 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.77bd483b-76b6-43f2-bb0b-b3f84449f929" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":1700,"costo":1347}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Jarabe 2% -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.c603901b-d67c-4feb-8dc5-e483b0e22b48" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":610,"costo":488}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Ibuprofeno 400 x 10 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.a87bd38e-558b-4813-9f1c-d76e321ff7b7" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":690,"costo":550}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Paracetamol 500mg -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.11d4f06b-6746-47c1-be16-7b7e702b9be5" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":1550,"costo":1256.04}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Tafirol x 10 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.efa337f5-20b2-408e-82d7-05676e38206e" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":1300,"costo":1036.8}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Amoxicilina x 8 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.9b9597af-942f-4206-922c-f674d032c7b5" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":630,"costo":501}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Omeprazol x 15 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.98ac31a8-9071-4987-9277-311312dd9682" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":500,"costo":396}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Frasco esteril gasana -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.3c54c588-9df9-465d-a46c-2939084d8dbc" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":2550,"costo":2053}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Gasa Syra x caja -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.1879d881-3665-4fa9-ad2b-ca116a9e3da4" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":1850,"costo":1483}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Bayaspirina x10 -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.7b0b9e79-726a-477c-9428-2e6745d1f4d0" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":1020,"costo":809}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Te Vivita Forte -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.ae05ae1b-77b4-4093-9934-9bcd6fee1ba0" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":2700,"costo":2150}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Cafiaspirina PLUS x10 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.ad52bbb4-24e0-4ed7-86eb-10b7c231999e" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":4400,"costo":3502}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Migral x 10 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.4f9bc52d-8999-4f25-a1a8-ae2bdc6ca500" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":3700,"costo":2956}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Anaflex PLUS x10 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.aa902bd9-ace8-46f7-a04f-16b1ca64d343" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":800,"costo":642}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Aspirinetas x14 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.64b1c79a-2377-4b71-af61-235f9595d565" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":5200,"costo":4103}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Buscapina perlas x10 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.7609ce95-523a-42eb-b32e-57a99db81361" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":2350,"costo":1863}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Tafirol plus x 8 -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.9ac769d4-4e5a-4138-9416-bb20971012b3" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":3380,"costo":2697}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Ibuevanol MAX x 10 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.93733064-3663-47fb-8509-fad2b9a95e6e" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":900,"costo":718}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Curitas x caja -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.bdd1860f-0bb1-4684-a83a-fcc84fda7b7e" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":2950,"costo":2366.5}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Anaflex x10 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.9dcb3b47-afa3-41ac-bb50-d70c6159f0bd" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":3950,"costo":3132}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Quraplus x 10 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.0cb66f45-d68b-4248-836b-71c42449b9db" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":2280,"costo":1822}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Ibuevanol Plus x 10 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.62e719ca-c2d4-4787-973b-3b25ca33db9a" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":2030,"costo":1621}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Geniol 1G x8 comp -> $R"; fi
R=$(curl -s -o /dev/null -w "%{http_code}" "https://oepqhdjuujfdlpjjktbs.supabase.co/rest/v1/presentaciones?id=eq.0efe4452-7b1e-42fb-8308-66600a04ceed" -X PATCH -H "apikey: $KEY" -H "Authorization: Bearer $KEY" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{"precio":430,"costo":340}')
if [ "$R" = "204" ]; then OK=$((OK+1)); else FAIL=$((FAIL+1)); echo "FAIL: Uvasal -> $R"; fi
echo "OK: $OK | FAIL: $FAIL"
